// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByZyZNYC115tasIvs4rwD9hTNbKqnCir4',
    appId: '1:1062797921318:web:ea08016fa1563f7f2b2ae7',
    messagingSenderId: '1062797921318',
    projectId: 'sdabjomreang-961c4',
    authDomain: 'sdabjomreang-961c4.firebaseapp.com',
    storageBucket: 'sdabjomreang-961c4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9vjmRX2_9MCS0YJnBeMEjQFP-lUvE7_s',
    appId: '1:1062797921318:android:23f301dc29f0111f2b2ae7',
    messagingSenderId: '1062797921318',
    projectId: 'sdabjomreang-961c4',
    storageBucket: 'sdabjomreang-961c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjH1MoDVGxjxEEjnK2hHRlNHwdgjHpdWo',
    appId: '1:1062797921318:ios:674705e164972a4c2b2ae7',
    messagingSenderId: '1062797921318',
    projectId: 'sdabjomreang-961c4',
    storageBucket: 'sdabjomreang-961c4.appspot.com',
    androidClientId:
        '1062797921318-snbpl5gi47qnsogsslvrahf9a1q287n2.apps.googleusercontent.com',
    iosClientId:
        '1062797921318-8mfgbs7kboknta052e82rh180jr1qr66.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotifyClone',
  );
}
